version: "3.2"

services:

  database:

    container_name: database

    image: mariadb:latest

    volumes:
      - ~/docker/mariadb/etc/mysql/conf.d:/etc/mysql/conf.d:ro

      - ~/docker/mariadb/var/lib/mysql:/var/lib/mysql

      - ~/docker/mariadb/var/log/maria:/var/log/maria

    environment:

      - MYSQL_DATABASE=chunjaeitlms

      - MYSQL_ROOT_PASSWORD=1234

      - MYSQL_ROOT_HOST=%

    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

    ports:

      - 3306:3306


  application:

    build: .

    restart: unless-stopped

    environment:

      SPRING_DATASOURCE_URL: jdbc:mariadb://database:3306/chunjaeitlms?useUnicode=true

      SPRING_DATASOURCE_USERNAME: root

      SPRING_DATASOURCE_PASSWORD: 1234

    ports:

      - 80:8080


    depends_on:

      - database


networks:
  default:
    name: chunjaeitlms-network
